# Site settings
title: Sydney Chin
description: A Resume Site
# baseurl: "/blog" # the subpath of your site, e.g. /blog
# url: "https://sidno.github.io/particle/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sydney Chin
user_description: cal poly blah
user_title: Student
email: sydneychin47@gmail.com
twitter_username: sidno4
github_username:  sidno
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
